namespace Companion.Modules.Tests.ResponseMocks
{
    public static class IEXResponseMock
	{
		public static string JSONResponse { get; set; } = @"[
              {
                ""avgTotalVolume"": 93373381,
                ""calculationPrice"": ""close"",
                ""change"": 0.57,
                ""changePercent"": 0.00378,
                ""close"": null,
                ""closeSource"": ""official"",
                ""closeTime"": null,
                ""companyName"": ""Apple Inc"",
                ""currency"": ""USD"",
                ""delayedPrice"": null,
                ""delayedPriceTime"": null,
                ""extendedChange"": null,
                ""extendedChangePercent"": null,
                ""extendedPrice"": null,
                ""extendedPriceTime"": null,
                ""high"": null,
                ""highSource"": ""15 minute delayed price"",
                ""highTime"": 1668805199998,
                ""iexAskPrice"": null,
                ""iexAskSize"": null,
                ""iexBidPrice"": null,
                ""iexBidSize"": null,
                ""iexClose"": 151.31,
                ""iexCloseTime"": 1668805199992,
                ""iexLastUpdated"": null,
                ""iexMarketPercent"": null,
                ""iexOpen"": 152.275,
                ""iexOpenTime"": 1668781800215,
                ""iexRealtimePrice"": null,
                ""iexRealtimeSize"": null,
                ""iexVolume"": null,
                ""lastTradeTime"": 1668805199992,
                ""latestPrice"": 151.29,
                ""latestSource"": ""Close"",
                ""latestTime"": ""November 18, 2022"",
                ""latestUpdate"": 1668805200919,
                ""latestVolume"": null,
                ""low"": null,
                ""lowSource"": ""15 minute delayed price"",
                ""lowTime"": 1668784066852,
                ""marketCap"": 2406739172220,
                ""oddLotDelayedPrice"": null,
                ""oddLotDelayedPriceTime"": null,
                ""open"": null,
                ""openTime"": null,
                ""openSource"": ""official"",
                ""peRatio"": 24.76,
                ""previousClose"": 150.72,
                ""previousVolume"": 80389400,
                ""primaryExchange"": ""NASDAQ"",
                ""symbol"": ""AAPL"",
                ""volume"": null,
                ""week52High"": 181.88,
                ""week52Low"": 128.65,
                ""ytdChange"": -0.13927328827599028,
                ""isUSMarketOpen"": true
              }
            ]";
	}
}
